repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0  # Use the ref you want to point at
        hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: debug-statements
        language_version: Python3

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: ''  # Use the sha / tag you want to point at
        hooks:
        - id: mypy

    -   repo: https://github.com/PyCQA/isort
        rev: ''  # Use the sha / tag you want to point at
        hooks:
        - id: isort
        args: ["--float-to-top"]

    -   repo: https://github.com/psf/black
        rev: 21.9b0
        hooks:
        - id: black
        args: [--safe]
